### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by bsherrill480** [brianjgeiger/markdown-it-video#20] opened 2016-07-14 09:02 UTC
Hey, I noticed that you run into an infinite loop with something like this.

```
cat @[youtube](dQw4w9WgXcQ)_
@[youtube](dQw4w9WgXcQ)_
```

I don't really understand markdown-it, but IIRC emphasis gets stuck in a loop because posMax < pos, but the text still satisfies the emphasis condition of being between "_". When I commented out the spots where state.posMax were changed, it no longer goes into the infinite loop (but I don't know what you were doing with posMax originally).

**Comment by rlancer** [comment] 2016-12-05 22:50
Got bitten by this too, this is the markdown

```text
 @[youtube](https://www.youtube.com/watch?v=vsw5s5gKsR0) 
Insane backend, front end, IoT, Arduino, and everything in between skills shown on this contribution. Harsh tackled this paid task with speed, clarity, and incredible intelligence. Not only did Harsha build out a full system from scratch (you can see the details in the thread) by architecting a way to tap into the Mixpanel API build a middle man webserver and pass the data live to our Arduino wirelessly, he was also able to _adapt_ to some serious issues faced with hardware limitiations, and used outside of the box thought process to STILL make it work. Looking forward to continuing to build this creation with Harsha. 

#[Back End Development](back_enddevelopment)
#[Arduino](313)
#[Arduino Uno](EJU7E93-b)
#[Hardware](hardware)
#[Software](1431)
#[Front End Development](front_end development) 
```

**Comment by industral** [comment] 2016-12-06 17:49
same to me. 100% CPU

**Comment by zipang** [comment] 2017-10-17 10:13
I can confirm that too.
As i intended to use this plugin in an interactive editor with markdown preview, i had to give up.
That's the most important bug to solve now ! :)

**Comment by brianjgeiger** [comment] 2017-10-17 13:14
Oh, for sure. It'll take a bit to figure that one out, though, but I'm going to try to get it this week.

**Comment by brianjgeiger** [comment] 2017-10-17 19:11
Related:

```
blah @[youtube](dQw4w9WgXcQ)
[12345678](blah.com)
```

Will result in a `blah` followed by a video followed by  `5678](blah.com)`

While something like
```
c @[youtube](dQw4w9WgXcQ)
@[youtube](dQw4w9WgXcQ)_
```
Seems to be the most efficient way to reproduce the infinite loop

**Comment by sloria** [comment] 2018-07-23 17:05
This is fixed in https://github.com/CenterForOpenScience/markdown-it-video/pull/34

**Closed as completed by sloria** 2018-07-23 17:05 UTC
Labels: bug, Confirmed
